### PR TITLE
Show revealed secrets on automap

### PR DESCRIPTION
**Pull request by kitchen-ace**

### CODE REVIEW

**Comment by kitchen-ace** [comment]
This is still not compatible with old Heretic saves: In Doom if there isn't enough data to read from the savegame, it just returns -1. In Heretic it calls I_Error. I'm not really sure what to do about that other than maybe completely rewriting SV_Read.
https://github.com/JNechaevsky/international-doom/blob/main/src/heretic/p_saveg.c#L137

I chose light blue for the revealed secret colour in Heretic, since the traditional green used in Doom is also used for locked doors.
HTIC01

**Comment by JNechaevsky** [comment]
I think it's completely okay to make saves from previous version incompatible, just a small warning will be needed to release notes. Please feel free to mark it ready once everything will be ready for merging - for some reason, I don't see a button to "approve" PR before it is ready for review (and is there such button?).

**Comment by kitchen-ace** [comment]
>I think it's completely okay to make saves from previous version incompatible

OK. In that case I will rewrite some stuff for Heretic so that the oldspecial is stored in the normal ArchiveWorld function.

>for some reason, I don't see a button to "approve" PR before it is ready for review (and is there such button?)

I think probably because I've set this as a draft, it can't be approved yet.

**Comment by JNechaevsky** [comment]
> OK. In that case I will rewrite some stuff for Heretic so that the oldspecial is stored in the normal ArchiveWorld function.

Nice idea, since it will be there forever and ever. 👍 My only though at the moment - is there possible way to apply small antialiasing for [this line](https://github.com/JNechaevsky/international-doom/pull/131/files#diff-a0d7c4b779fa1dfd4ec779c53aafc3fe19547b994e428e5470a28c7ffedaf96eR309)? Probably not, as 207 and 208 colors are notably different.

**Comment by kitchen-ace** [comment]
Actually I just realized I can check for the save game terminator byte before reading oldspecials, so we can preserve compatibility after all. Unless you think keeping it cleaner for the future is more important -- like you said, it'll be there forever!

>My only though at the moment - is there possible way to apply small antialiasing for [this line](https://github.com/JNechaevsky/international-doom/pull/131/files#diff-a0d7c4b779fa1dfd4ec779c53aafc3fe19547b994e428e5470a28c7ffedaf96eR309)?

I think the AA on both secret sector colours can be improved a little, I was going to try it later and make a separate commit if I got anywhere.

**Comment by JNechaevsky** [comment]
P.S. Hm, need to think, since we are always in TrueColor mode, we can map any RGB colors without palette dependency, like [here](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/id_func.c#L768-L774). It's not a scope of this PR, but I'll deffinitly have to experement, this could make Heretic line antialiasing much better in theory.

**Comment by JNechaevsky** [comment]
> Actually I just realized I can check for the save game terminator byte before reading oldspecials, so we can preserve compatibility after all. Unless you think keeping it cleaner for the future is more important -- like you said, it'll be there forever!

If this means keeping compatibility with old save games, then it worth gold. 🙂 However, if it will complicate things, then just please omit it and proceed as you would like to.

> I think the AA on both secret sector colours can be improved a little, I was going to try it later and make a separate commit if I got anywhere.

Sure, if you wish to. If my idea with RGB mapping will work, then antialiasing values will have slightly different approach, guarded with `#ifdef CRISPY_TRUECOLOR`. Paletted code is still fully working, I'm trying to keep it just in case.

**Comment by kitchen-ace** [comment]
>If this means keeping compatibility with old save games, then it worth gold. 🙂 However, if it will complicate things, then just please omit it and proceed as you would like to.

Not complicated, just a little ugly. If it turns more changes to the savegame format are needed, maybe it's worth looking at versioning and sweeping some of this dirt under the rug ;) but for now it'll do!

**Review by JNechaevsky — APPROVED** [review]
LGTM, thank you! Please feel free to merge, if it's all done. ✨

**Comment by kitchen-ace** [comment]
BTW

>Hm, need to think, since we are always in TrueColor mode, we can map any RGB colors without palette dependency, like [here](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/id_func.c#L768-L774).

Does this mean that even when not using truecolor rendering, inter ports are still internally using truecolor, and so there's no performance difference between the two? I noticed some big FPS drops in certain situations in Hexen (using lots of the fighter's Quietus weapons up close on bosses), even when not using truecolor rendering, and that would explain why.

**Comment by JNechaevsky** [comment]
Indeed, when TrueColor is just disabled in options menu, the engine itself is still on TrueColor rails. Basically, it's just renders game world via `COLORMAP` colors and make custom `COLORMAP`s working properly. Translucency, however, is still calculated dynamically. 

As about Quietus, honestly, it's my huge oversight. Probably, you have "Extra translucency" enabled? It makes all green projectiles translucent, and when point-blank attack happens, FPS dropping dramatically low, even on i7-12700f. Removing [this](https://github.com/JNechaevsky/international-doom/blob/main/src/hexen/info.c#L9319) `MF_EXTRATRANS` flag should help, and looks likes it have to be done.

**Comment by kitchen-ace** [comment]
>Probably, you have "Extra translucency" enabled? It makes all green projectiles translucent, and when point-blank attack happens, FPS dropping dramatically low, even on i7-12700f. 

Yep, taking that off helps quite a bit. A common strategy to deal with the Heresiarch, the most boring boss in all Doom engine games, is to put on invulnerability, then spam Quietus while also throwing flechettes as fast as possible. On my i7-11800H I could get down to around 12 FPS if I was quick enough and kept him in view!

Taking out `MF_EXTRATRANS` is from Quietus probably a good idea then, unfortunately.

**Comment by JNechaevsky** [comment]
Oh my.. According to render counters, it's not just 5 green projectiles, it's about **21** in total, presumably 5 big clouds and 15 extra small. Better I disable original translucency for them too, until some serious optimization happens.

**Comment by JNechaevsky** [comment]
Could you please check, doesnt' it looks bad?
```diff
+++ inter-doom/src/hexen/info.c	Sun May  5 19:11:50 2024
@@ -9311,16 +9311,20 @@
      SFX_FIGHTER_SWORD_EXPLODE, // deathsound
      30 * FRACUNIT,             // speed
      16 * FRACUNIT,             // radius
      8 * FRACUNIT,              // height
      100,                       // mass
      8,                         // damage
      SFX_NONE,                  // activesound
-     MF_MISSILE | MF_NOBLOCKMAP | MF_NOGRAVITY | MF_DROPOFF |    // flags
-     MF_EXTRATRANS,             // [JN] Extra translucency (Quietus big green smoke)
+     MF_MISSILE | MF_NOBLOCKMAP | MF_NOGRAVITY | MF_DROPOFF    // flags
+#ifndef CRISPY_TRUECOLOR
+     | MF_EXTRATRANS,           // [JN] Extra translucency (Quietus big green smoke)
+#else
+     ,                          // Too expensive in TrueColor mode...
+#endif
      MF2_NOTELEPORT | MF2_IMPACT | MF2_PCROSS   // flags2
      },
 
     {                           // MT_FSWORD_FLAME
      -1,                        // doomednum
      S_FSWORD_FLAME1,           // spawnstate
      1000,                      // spawnhealth
@@ -9339,15 +9343,20 @@
      SFX_NONE,                  // deathsound
      0,                         // speed
      20 * FRACUNIT,             // radius
      16 * FRACUNIT,             // height
      100,                       // mass
      0,                         // damage
      SFX_NONE,                  // activesound
-     MF_NOBLOCKMAP | MF_NOGRAVITY | MF_SHADOW,  // flags
+     MF_NOBLOCKMAP | MF_NOGRAVITY  // flags
+#ifndef CRISPY_TRUECOLOR
+     | MF_SHADOW,               // Quietus small green smoke
+#else
+     ,                          // Too expensive in TrueColor mode...
+#endif
      0                          // flags2
      },
 
     {                           // MT_CW_SERPSTAFF
      10,                        // doomednum
      S_CSTAFF,                  // spawnstate
      1000,                      // spawnhealth

```

**Comment by kitchen-ace** [comment]
>Could you please check, doesnt' it looks bad?

Looks fine. The bright green from additive blending definitely looked cool, but not worth the FPS hit. The small flame puffs no longer being transparent is a noticeable change, but it doesn't look bad, just slightly different than normal; a small price to pay for truecolor software rendering.

**Comment by JNechaevsky** [comment]
Still thinking that compiling executable with both TrueColor and full palette-support is possible, but most likely it will lead to big amount of hitting `if (vid_truecolor)` (easier, bad) conditions or function pointers (harder, more complicated). Really no idea how to implement LUT for translucency, that's the only really necessary thing to solve possible performance penalties...

Last thing I want to annoy with this PR: could you please prove a line for changelog? Default behaviour of "Mark revealed sectors" is changed, but it's okay since now it have more fair approach.

**Comment by kitchen-ace** [comment]
>Last thing I want to annoy with this PR: could you please prove a line for changelog? Default behaviour of "Mark revealed sectors" is changed, but it's okay since now it have more fair approach.

I don't see a changelog file in the inter-doom sources anywhere. If you just wanted me to write a line here:

"Mark secret sectors" will now always show secret sectors after they've been found on the automap, and optionally before as well. (Doom, Heretic)

feel free to reformat as needed.

**Comment by JNechaevsky** [comment]
It's perfect, thanks! Oops, changelog is placed as draft in [Releases](https://github.com/JNechaevsky/international-doom/releases) section, but since it's a draft, it is visible only to me. Worth to create sometheng like `changelog.md` file then? Ideally to setup Actions as well, but never tried to do it by myself.

**Comment by kitchen-ace** [comment]
Aha, as long as I know where to find it, it's fine there. I will update it in a few minutes if you haven't done so already by then. If you end up having more approved collaborators then it might be worth changing to something more standardized; for now when it's just me, I'm happy to follow whatever system you want to use.

>Ideally to setup Actions as well, but never tried to do it by myself.

You would know more about this than I would I'm afraid!

**Comment by kitchen-ace** [comment]
>Still thinking that compiling executable with both TrueColor and full palette-support is possible, but most likely it will lead to big amount of hitting if (vid_truecolor) (easier, bad) conditions or function pointers (harder, more complicated). 

In my opinion: I wouldn't bother. Truecolour software mode is one of the main distinguishing features of International Doom right now. If truecolour translucency is the only major performance hit, even if improving it might be a very long way off, focusing on solving that is the better long-term approach. (Of course if you disagree you're welcome to do it however you want, but you don't sound that enthusiastic about filling the code with if statements or complicated pointers everywhere!)

**Comment by JNechaevsky** [comment]
> Aha, as long as I know where to find it, it's fine there. (I can see it.) 

Super, please feel free to update/rewrite it as much as needed, some lines can be deffinitly unclear. It will not require any kind of pull request. 

As about TrueColor: I need to make a little experement, to: 1) see if render will be able to toggle between real palette/TrueColor mode, and 2) see amount of crazy changes and conditions in the code. If everything fails, then the only person who can help is Fabian. But honestly, I'm afraid to annoy him with stuff like "could you please write some code", at least without suggesting something in return. Efforts and personal time are also important things. 🙂

**Pull request merged**
