### PR TITLE
Heretic and Hexen: update visplanes drawing code

### PR DESCRIPTION
**Pull request by JNechaevsky**
Straight from Doom, where it's more compact and slightly better polished. This should take care of https://github.com/JNechaevsky/international-doom/issues/77.

### CODE REVIEW

**Comment by kitchen-ace** [comment]
Does this need applying to Crispy Heretic?

**Comment by JNechaevsky** [comment]
Probably not, the real problem was with my incorrect change of Crispy code.

**Comment by JNechaevsky** [comment]
But thinking more... Better I'll double check. There are no "Swirling Liquids" feature available, so I have to remember how to compose `ANIMATED` lump to make vanilla liquids swirling. Once done, I can simply but a brick on "go to next level" key and scroll  maps of htchest.wad. Such high-tech approach was used yesterday for testing corrected visplanes code. 😀

**Comment by JNechaevsky** [comment]
It's seems to be safe. Here's a wad with `ANIMATED` lump, which represents ID's scrolling liquids I was using for ~5 minutes of levels scrolling: [htic_anims.zip](https://github.com/JNechaevsky/international-doom/files/14229963/htic_anims.zip)

**Pull request merged**
