### PR TITLE
Brightmaps revisited

### PR DESCRIPTION
**Pull request by JNechaevsky**

### CODE REVIEW

**Comment by JNechaevsky** [comment]
@fabiangreffrath, my results so far (before/after):

1. BFG world sprite.
image 
image

2. BFG firing sprite, barely notable line of red pixels.
image
image

3. Full green range for `SW2STONE`, separated for Doom 1. No changes for Doom 2 version because of possible straying pixels (might be interesting for @bradharding as well).
image
image

The rest of everything seems to be perfectly balanced in terms of nice looking / reasonable amount of bright pixels. The only difference is that we have a slightly different set of texture b-maps between our ports, but this is the matter of taste of course.

**Comment by fabiangreffrath** [comment]
If there is anything that you see fit for applying in Woof, please feel free to file a PR.

**Comment by JNechaevsky** [comment]
Will do, thank you, just a little bit later. Corrections from above fits for sure, I was afraid of big diff or possibly broken `redonly` textures, but in the end changes are tiny and not _too_ notable in terms of visual difference, so no "what the heck?!" effect should happen at users.

As about additional textures - probably before PRing them, the best way will be few showcase maps to show how they will look like in action. Screenshots or recorded video is not good enough for such case.

**Comment by bradharding** [comment]
Thanks for tagging me, Julia. I'll make the change to DR as well. :)

**Pull request merged**
