### PR TITLE
Add circular flowing effect for swirling liquids

### PR DESCRIPTION
**Pull request by JNechaevsky**
Revived my old feature, now it should be even faster as no coords calculation is needed at all, it's now using look-up table. In general, this effect is not very noticeable unless looking down or standing in a sector with "deep water" effect, but still bring some reasonable smoothness in swirling animation. 

https://github.com/JNechaevsky/international-doom/assets/21193394/c6aa7791-20e7-41ed-95e3-66a6574e1d79

### CODE REVIEW

**Comment by Meerschweinmann** [comment]
Hooray, something new to look at and compare 😊 I will have a live-look at it later when i am back to my PC.
Do you use another Colorpal? The blue looks not like DOOMs oversaturated blues.

**Comment by JNechaevsky** [comment]
Sure, it's a small detail that doesn't really stand out until you take a closer look. It's different blue colors indeed, here it is: https://jnechaevsky.github.io/projects/prussian-blue/index.html
I have seen it couple of times in different wads and somehow felt in love into it. 🙂

**Comment by Meerschweinmann** [comment]
I have loaded "old" and actual Inter-DOOM at the same time and Alt-Tabbed between them. It seems the new swirl effect moves the whole swirling texture additionally in a slight circle. The difference is hard to notice, when you don't stand in or nearby the water, but i like it.

The prussian-blue wad is saved. Much much better than those oversaturated blues DOOM delivers originally :)

BTSX and Ancient Aliens have a nice PLAYPALs too, because they contain a wider range of colors for texture making, but to use them you have to convert all the original assets with Slade3. And then every other pwad with textures does not look right.

**Comment by kitchen-ace** [comment]
Wow, that looks great on Heretic's moving water flat!

**Comment by Meerschweinmann** [comment]
Hexen liquids look nice too. The new modified swirling is a nice detail for those who take a closer look.

**Comment by JNechaevsky** [comment]
Cool, thanks! In previous 6.x version I did some per-vanilla level definitions, like in E1M5 slime was scrolling in north direction, but can't go this way now, it's again a direct path to code overbloating. 😕

> EDIT: Ah, "circular flowing", circle. Now i get it. Language-barrier again. 

Honestly, I'm not even sure how to call such "animation" on my native language. If translated, it's probably something like... "rocking water"? ... Erm, excuse me, "rocking"??? Language barrier indeed! 😀

P.S. Joke of the day!
<details>

image

</details>

**Comment by Meerschweinmann** [comment]
I was blind with circular. In my native language the translation is written very similar. I really should have known it, even the translation is the more academic sounding variant of the word i had used :)

When my russian neighbors and me communicate, there are sometimes moments where we look surprised, because sometimes the translation says the total different from that what we want to say.

Should i see the Strife logo as something coming up?  ;) To be honest, Strife was never that game for me in comparision to the other three ID-Tech1 games, i had played endless times the last 30 years. I had never ended that game. But i would give it a chance when Inter-Strife should come and do a playthrough to know what so many people talk about.

**Comment by JNechaevsky** [comment]
Not sure if it's really coming up as Inter, but I was curious how such icon may looks like. I have tried to start Inter-Strife for about 3 or 4 times, but never gets far. Maybe this time something will be changed since I don't need to break my head on translation and stuff, just an engine and render, which in return, is most interesting part for myself. If you ask me, how much time I spent on playing new Inter-Hexen, I can honestly answer: "no longer than 5 hours in total", while working on in took about two extensive months. Amazing visuals and absolutely stressful gameplay if playing on local Ultra-violence. 🤯

To be honest from my side, I have finished vanilla Strife just once, somewhere in ~2002. No, simply not my game, alas... But I have to finish the last chapter of Crispy true color, which is a Strife supports. And this journey have [started](https://github.com/fabiangreffrath/crispy-doom/commits/strife__truecolor/). 🤓

**Comment by kitchen-ace** [comment]
I've never been much of a fan of Strife either. I bought Strife Veteran Edition when it came out, just to have a legal copy when it became possible, but I have yet to play it even. I do think it looks quite good for a Doom engine game, but playing it is just not that fun.

**Comment by JNechaevsky** [comment]
Yep, if I'll get my hands on Inter-Strife, swirling liquids and extra brightmaps/translucency will be done for sure, even by making a very brief look into game a huge potential for such visual improvements can be seen. But from another hand, StrifeVE offers own amazing features and most importantly - fixes of vanilla soft-locks. I never tried it, just watched Civie11's video about Strife.

Oh well, let's finish with Crispy Strife first. Surprisingly, it took just 4 hours to port everything possible and make the game playable (except screen cross-fading).

**Comment by Meerschweinmann** [comment]
As i said, i would give Strife another chance, because many people say it is a good game. Eventually i did not play it far enough. And then Inter-Strife would be my way to go. 

Another question to Strife. Technically it should be the most advanced ID-TECH1 game. Can the assets and maps changed to make a Heretic or DOOM based with the Strife Engine? That could be an interesting thing.

**Comment by Meerschweinmann** [comment]
Hmm, i have looked with UDB and Slade3 what is in those Strife WADs. I have my doubts that Strife is even more enhanced than Hexen. There are no ACS scripts and the map format is simple DOOM format. Polyobjects seem to be not in there too, or i have not found some. The PLAYPAL is more versatile than DOOMs.

**Comment by kitchen-ace** [comment]
@Meerschweinmann different set of features. No polyobj support, I think more limited scripting than Hexen though there is a scripting system (look at all the SCRIPTxx lumps), but dialogue and RPG-type permanent upgrades for the player. Also a basic form of brightmaps with the COLORMAP, which is pretty cool.

You could maybe change things around to make a Doom-like map; there is a Dehacked-like program called [SeHackEd](https://www.doomworld.com/sehacked/), though it's less functional than Dehacked is. Doom 1's bestiary is easy enough to approximate but I don't know how close you could come to things like Arch-viles with it.

**Comment by Meerschweinmann** [comment]
@kitchen-ace different set of features seems to be the right description. I thought strife offers everything Hexen offers plus the RPG elements and some new line/sector actions.
But unfortunately it is not so.

Back in the days it was something magic to "upgrade" DOOM to the newer engines. I can remember that we converted E1M1 with DOOM textures in Duke Nukem 3D and Heretic. But the monsters and weapons were the part we did not get to work as intended. Hexen was the most interesting, but we had no tools that supported Hexen, and did not know that this game used scripts.

Today there is normally no reason to do that, because there are source ports that can do BOOM, ACS or portals/3D floors, with more functionality Hexen or Strife can offer.
But i find it interesting to do those things that we wanted to do back in the days, with all those limitations. And today there are many tools we had not in the 90s or did not know, because there was no internet. Only Coverdiscs from magazines that could contain something useful.

**Pull request merged**
