### PR TITLE
Implement selective autoload

### PR DESCRIPTION
**Pull request by JNechaevsky**
For .wad and .deh files (not lumps!). Allow to choose autoload options:
* Off (disable autoload)
* IWAD only (current and default behavior)
* IWAD and PWAD (create all the folders)

Thanks @Meerschweinmann for suggestion!

### CODE REVIEW

**Comment by JNechaevsky** [comment]
@Meerschweinmann, was it what you wish to have? Please, check on your side, it's all done.

**Comment by Meerschweinmann** [comment]
Hi Julia. Do you have a compiled version for me.

I have compiled it this morning as usual and get random crashes everywhere. When the demo starts, when going into the menu. Sometimes i come one step deeper in the menu and it crashes. Starting Sigil 2 without any loaded assets crashes. Unfortunately something seems wrong with the version i have compiled myself. I had made a fresh ID folder too, same problem :(

**Comment by JNechaevsky** [comment]
Should be fixed now in latest commit. We have screwed up in font drawing function.

**Comment by Meerschweinmann** [comment]
Ah, good. I will test it later.

**Comment by JNechaevsky** [comment]
Thanks! Do not hurry, though. It's now on "MISCELLANEOUS" submenu. Looks likes now there is a lot of space to add some ~~useless~~ uncategorized options, but I have no ideas which exactly. If nothing will happens, then we can just rename it to "Autoload options" or somethings. In other words, I'm all open for ideas and recommendations.

**Comment by Meerschweinmann** [comment]
Heyhey, compiled it after your last change again and now it works great!

Had loaded Sigil and Sigil II together and Inter-DOOM loaded all three widescreen asset files.

**Comment by JNechaevsky** [comment]
Great news, thank you! 🤗

**Comment by Meerschweinmann** [comment]
I have to say thank you 😃

**Pull request merged**
