### PR TITLE
Add `savegames_path`, `screenshots_path` config variables and `-shotdir` parameter

### LINKED ISSUE #125: add '-shotdir' command line parameter
There's people (like me) that use the '-savedir' parameter to specify custom savegame folders (tipically, dedicating one to each iwad/pwad combo).
With other ports we can do the same with screenshots by using the '-shotdir' parameter, thus saving all content generated by the same play session being in the same directory.

It would be nice if inter-doom/heretic/hexen made this possible as well, either by forcing screenshots to be written to the same folder as the savegames (when the user has specified a custom/specific one) or by adding the '-savedir' parameter proper.

Thank you!

### PR DESCRIPTION
**Pull request by JNechaevsky**
Needs some polishing. Probably worth to make `D_SetDefaultSavePath` global for all three games, but it's slightly different for Hexen.

Fixes #125, thanks @liPillON for suggestion!

### CODE REVIEW

**Comment by JNechaevsky** [comment]
@liPillON, if you are able to compile by yourself, could you please check if it is what was needed? Seems to be working fine, but I have to double check it on Linux once I'll get home.

Ah yes, as about "per-pwad" stuff, please do not request it, it's a kind of "over my dead body" thing. 😀

**Comment by liPillON** [comment]
hey, cool! You went in and implemented this, thank you!

Unfortunately I'm not able to test this on my own right now, but having taken a look at the changes I would say that this is exactly what I was suggesting. 

Forget about automatically set up "per-pwad" paths, I usually let the launcher manage that - all it needs are the command line parameters to tap into

**Comment by JNechaevsky** [comment]
No problem! It can wait as much as needed, there are no plans to release any updates soon. Linux seems to be fine, too, but the only thing - both `savegames_path` and `screenshots_path` will appear in existing config file(s) only after the game will run once. They will be placed right below existing `music_pack_path` variable, on 3rd and 4th lines.

"Per-pwad" has own story. I started working on Heretic and was carefully picking the code from Crispy. Render code was more or less formed at that point, and I have prepared about dozen of different testing PWADs with funny names like "her-pln", "her-opn", "her-kaboom" and so on. Much later, when I take a look into `autoload` folder, I was a like a... "Wha-?! I didn't asked for creating such folders!!!" and decided to decline autoloading per PWADs. 😅

**Comment by JNechaevsky** [comment]
Phew, was a quite new experience with constructing paths and make config file happy, trailing backlashes are evil. 👹
All done now, thanks again for suggestion!

**Pull request merged**
