### PR TITLE
Heretic: fix hitscan/missile puffs disappearing in certain areas

### PR DESCRIPTION
**Pull request by JNechaevsky**
This is complex fix:
- Hitscan puffs now able to appear on floor/ceiling, even when bumped in front of back side 2-sided line (🤯...).
- Missile explosions no longer disappears on back sides to 2-sided lines, Phoenix Rod explosions are having just a visual effect in such cases.
- Safe for longest full 1-5 episode runs demos, but I still want to check it manually in the game.
- As small diff as possible.

### CODE REVIEW

**Comment by kitchen-ace** [comment]
Nicely done, I tried making some test case scenarios that would desync (e.g. a shootable switch on a far away ledge, that triggers when you shoot the ceiling, because the impact of the shot "travels" along the ceiling to hit it) but everything I could think of works properly. Great work!

**Comment by JNechaevsky** [comment]
All credits goes to Fabian, I'm just carefully ported his code with exactlly one difference: there is no `acv` [action pointers](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/d_think.h#L40-L47) in Hereric. But I honestly not 100% sure what they are stands for. 🙂

What is really cool here is a ~~rocket~~ flame orb explosions which, unlike Doom, is able to play full animation sequence but this is just because of radius damage is invoked earlier than in Doom's rocket explosion.

There is a small trick, you even don't need to watch demos to be sure that desync is not happening. I'm grabbing couple of full episode runs from [DSDA-Archive](https://dsdarchive.com/wads/heretic) and running them like this via batch file:
```
start inter-heretic.exe -nodraw -console -timedemo NNNNN1.lmp
pause
start inter-heretic.exe -nodraw -console -timedemo NNNNN2.lmp
pause
```

If every run prints a string like `P_SetupLevel: E5M8, Heretic format (BSP), ...` then OK, this means that game successfully gets into last level. If you are not on Windows and have a native OS console, you even don't need to use `pause` in batch file and provide `-console` command line parameter (it's compiled for Windows only).

And, if @fabiangreffrath don't mind, I'll gladly carry these changes to Crispy Heretic.

**Comment by kitchen-ace** [comment]
`-timedemo` is good to know about! But having watched most of the Heretic runs on DSDA, I know there are some situations that rarely or never come up -- I think there are only 2 or 3 demos where players look up or down at all in fact.

**Comment by JNechaevsky** [comment]
True, true, I remember this case. AFAIR, looking down was used to make a rocket-boost by shooting to feet to gain a speed boost. This is basically means that playstate's (not rendering's) looking amplitude should not be touched to keep demo sync. I made this mistake back in past Inter-Heretic versions, but honestly, I'm almost never have any kinds of nostalgias and regrets about the "past" so all of that was torn to oblivion. Except gained experience, which is helping nowadays a lot.

**Comment by fabiangreffrath** [comment]
> And, if @fabiangreffrath don't mind, I'll gladly carry these changes to Crispy Heretic.

Sure, why not. 👍

**Pull request merged**
